INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('4e626580-da73-41f7-95f2-d72c864b3c63', 'RG', 1, 'Voce e um especialista em extracao de dados de documentos de identidade brasileiros (RG - Registro Geral / Carteira de Identidade).
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('fd4d501c-c804-4955-979a-2d028c0d947a', 'CNH', 1, 'Voce e um especialista em extracao de dados de Carteiras Nacionais de Habilitacao (CNH) brasileiras.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('4c42ca45-4572-4ce1-9234-df42892f5e0d', 'CNDT', 1, '## REGRAS OBRIGATORIAS
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('574db396-d029-4fa0-b04d-5c4d58820ef1', 'MATRICULA_IMOVEL', 1, '# PROMPT PARA ANALISE DE MATRICULA DE IMOVEL
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('dfd8a5f5-0c04-4dea-8ac7-ef7daf5c2b2a', 'CERTIDAO_CASAMENTO', 1, 'Analise esta Certidao de Casamento brasileira.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('135918a8-477f-4892-bfef-fbc366b046ae', 'CERTIDAO_NASCIMENTO', 1, '## REGRAS CRITICAS - LEIA COM ATENCAO
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('18ab08f5-bbd8-4ea2-bf88-97d596e4e122', 'MATRICULA_IMOVEL', 2, '# PROMPT COMPACTO PARA MATRICULA DE IMOVEL
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('3fbda1f5-89fd-410d-b639-aa3be8bb6d14', 'ESCRITURA', 1, 'Analise esta Escritura Publica (compra e venda, doacao, permuta, etc).
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('e4e02e27-61c7-4aca-90dd-b443815da4f8', 'ESCRITURA', 2, 'Analise esta Escritura Publica e extraia TODOS os dados estruturados.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('268fa747-2f0b-4409-a77d-6c10131d770f', 'COMPROMISSO_COMPRA_VENDA', 1, '# PROMPT PARA EXTRACAO DE COMPROMISSO DE COMPRA E VENDA DE IMOVEIS
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('45a3ecc3-395e-4f3a-96dc-d3b4b82e80ae', 'IPTU', 1, 'Analise este documento de IPTU ou Certidao de Dados Cadastrais do Imovel.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('d8f9e708-2357-449f-b47f-c4ec23975bd2', 'CND_MUNICIPAL', 1, 'Analise esta Certidao Negativa de Debitos Municipais / Certidao de Tributos Imobiliarios.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('c119f953-cc6f-42db-85f0-922f9236b748', 'PROTOCOLO_ONR', 1, 'Analise este protocolo/comprovante do Operador Nacional do Registro (ONR/SAEC).
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('3e93b70b-7189-459c-b7f5-60cdd5140ef1', 'ASSINATURA_DIGITAL', 1, '================================================================================
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('15f47d4f-e4d0-4013-a1df-547f7a7fc029', 'MINUTA_VENDA_COMPRA', 1, 'Voce e um especialista em minutas de escritura publica brasileira, especificamente em escrituras de compra e venda de imoveis.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('33a8e0a0-dc31-4eb1-8dbb-5558573fa1f1', 'MINUTA_DOACAO', 1, 'Voce e um especialista em minutas de escritura publica brasileira, especificamente em escrituras de doacao de imoveis.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('f88513b9-32f6-4a04-bd76-0fa5c9eda63c', 'MINUTA_PERMUTA', 1, 'Voce e um especialista em minutas de escritura publica brasileira, especificamente em escrituras de permuta de imoveis.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('dbffa117-e390-49a3-b2f0-73a2c00218d9', 'CLASSIFICATION', 1, 'Voce e um especialista em documentos brasileiros de cartorio e registro de imoveis.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('21a086de-dfaf-41d5-aaff-6e98339c0c49', 'RG', 3, 'Voce e um especialista em extracao de dados de documentos de identidade brasileiros (RG - Registro Geral / Carteira de Identidade).
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('4055ef9c-b356-4e6a-9873-7eff0b8e9a46', 'CERTIDAO_CASAMENTO', 3, 'Analise esta Certidão de Casamento brasileira e extraia TODOS os dados visíveis.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('e2c3a6a2-84e4-4078-9e6c-8b9a0463bb4b', 'CNH', 2, 'Voce e um especialista em extracao de dados de Carteiras Nacionais de Habilitacao (CNH) brasileiras.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('e63dd273-e145-4056-adfb-1d7dac02ee57', 'RG', 2, 'Voce e um especialista em extracao de dados de documentos de identidade brasileiros (RG - Registro Geral / Carteira de Identidade).
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('6e8d3a81-b472-45dc-9a64-639635ab0b92', 'MATRICULA_IMOVEL', 3, '# PROMPT V2 - MATRICULA DE IMOVEL (JSON-ONLY)
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('e6591842-01d5-4dcd-94c2-b004ba5e9314', 'CNDT', 2, 'Voce e um extrator especializado em Certidoes Negativas de Debitos Trabalhistas (CNDT) brasileiras.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('2c285ca2-75d0-4805-9188-d6b47368b611', 'CERTIDAO_NASCIMENTO', 2, 'Analise esta Certidão de Nascimento brasileira e extraia TODOS os dados visíveis.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('ae15fcc2-a20e-4422-afcc-d556813655d3', 'CERTIDAO_CASAMENTO', 2, 'Analise esta Certidao de Casamento brasileira.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('d17846eb-19ea-4f2c-a38d-35f621e34ef9', 'PROTOCOLO_ONR', 2, '================================================================================
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('99f57761-27ae-4e97-8516-77f47b1599bf', 'CND_MUNICIPAL', 2, 'Voce e um extrator especializado em Certidoes Negativas de Debitos Municipais e Certidoes de Tributos Imobiliarios brasileiras.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('a7710caf-c5a2-4587-b1d9-1a3a502b9b54', 'IPTU', 2, '# PROMPT V2 - IPTU / CERTIDAO DE DADOS CADASTRAIS (JSON-ONLY)
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('693eced3-3432-443e-9fb4-44816a5ad9c7', 'VVR', 2, '# PROMPT V2 - VALOR VENAL DE REFERENCIA (JSON-ONLY)
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('e4ec8e39-8cd4-497e-aede-baa329488415', 'COMPROVANTE_PAGAMENTO', 2, 'Voce e um extrator especializado em comprovantes de pagamento brasileiros (recibos, transferencias, PIX, boletos, guias de arrecadacao, tributos).
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('c9f2f71a-5412-42b0-abdf-1f82c8760b63', 'VVR', 1, 'Analise esta consulta de Valor Venal de Referencia (VVR) do imovel.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('f6659132-22c7-4ec6-8d4b-008213f42141', 'ASSINATURA_DIGITAL', 2, '================================================================================
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('00554c7a-8932-4499-afac-a941ec5b7b1f', 'COMPROVANTE_PAGAMENTO', 1, 'Analise este comprovante de pagamento (recibo, transferencia, PIX, boleto, guia de arrecadacao, etc).
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('703012cd-dd39-4a56-a21a-2c90713806aa', 'GENERIC', 2, '================================================================================
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('c3f15abd-9c1c-4e1e-b1db-69c2a80c6b05', 'DESCONHECIDO', 2, '================================================================================
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('cad637d8-87dd-4cf5-9ef8-d3fa9c107ac3', 'ITBI', 2, '## INSTRUCOES DE SAIDA - LEIA PRIMEIRO
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('d7adf178-ebc2-4a3e-b2bc-5aebbb1311ae', 'GENERIC', 1, 'Voce e um especialista em analise de documentos brasileiros. Este documento NAO possui um prompt especifico, portanto voce deve fazer uma analise generica mas detalhada.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('d915b8e1-aead-4904-8265-fe5caccd54bd', 'DESCONHECIDO', 1, 'Voce e um especialista em analise e catalogacao de documentos brasileiros. Este documento foi classificado como DESCONHECIDO pelo sistema, o que significa que nao foi possivel identifica-lo automaticamente.
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('9f98f290-4e93-4c0b-be07-fdc4e5e235e4', 'ESCRITURA', 4, '## INSTRUCOES DE SAIDA - LEIA PRIMEIRO
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('2e0dd30b-0619-4886-a0e9-028e8b1f6367', 'COMPROMISSO_COMPRA_VENDA', 2, '## INSTRUCOES DE SAIDA - LEIA PRIMEIRO
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('337aeefd-6919-4500-a7c2-9ae3fb82d5ec', 'ITBI', 1, '## REGRAS OBRIGATORIAS
INSERT INTO public.agent_prompts (id, tipo_documento, versao, prompt_text, descricao, ativo, created_at, updated_at) VALUES ('548dc5c7-1650-4d26-8871-b6dba544232d', 'ESCRITURA', 3, 'Voce e um especialista em analise de escrituras publicas brasileiras. Sua tarefa e analisar PROFUNDAMENTE esta escritura e extrair TODOS os dados em formato JSON estruturado.
