INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('1267a5ea-81b5-47a1-914a-0c6c35da8779', 'rg', 1, 'Voce e um especialista em extracao de dados de documentos de identidade brasileiros (RG - Registro Geral / Carteira de Identidade).
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('b5c74e75-65a2-4b72-b2be-5ae57595dffe', 'cnh', 1, 'Voce e um especialista em extracao de dados de Carteiras Nacionais de Habilitacao (CNH) brasileiras.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('40a5f3cc-6fd2-4368-b914-ce45a2d10026', 'certidao-casamento', 1, 'Analise esta Certidao de Casamento brasileira.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('e0c67089-03ea-49e5-bc02-d8aad1346b12', 'certidao-nascimento', 1, '## REGRAS CRITICAS - LEIA COM ATENCAO
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('41487b24-4e29-4e1f-98a6-ac7c13db737a', 'matricula-imovel', 1, '# PROMPT PARA ANALISE DE MATRICULA DE IMOVEL
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('9014464f-52da-4e74-9469-2ef0b1155545', 'itbi', 1, '## REGRAS OBRIGATORIAS
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('e6e2758a-c82c-4a7c-b135-e4cdfe553663', 'iptu', 1, 'Analise este documento de IPTU ou Certidao de Dados Cadastrais do Imovel.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('a88db4f3-8ab8-42b5-8f26-d985ac247b61', 'escritura', 1, 'Analise esta Escritura Publica (compra e venda, doacao, permuta, etc).
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('3c3904ad-7bcf-4ad7-a75d-5ac43020726e', 'compromisso-compra-venda', 1, '# PROMPT PARA EXTRACAO DE COMPROMISSO DE COMPRA E VENDA
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('aaa6dc15-0483-4a6a-b888-c455e2789709', 'contrato-social', 1, 'Analise este Contrato Social ou documento empresarial brasileiro.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('ff080aba-abe8-4b4e-9e0b-c54b6f189846', 'cndt', 1, '## REGRAS OBRIGATORIAS
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('d886f9af-39e5-4052-9230-54cd0e7317f0', 'rg', 2, 'Voce e um especialista em extracao de dados de documentos de identidade brasileiros (RG - Registro Geral / Carteira de Identidade).
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('66b3519c-4423-41b0-9819-807097a67506', 'cnh', 2, 'Voce e um especialista em extracao de dados de Carteiras Nacionais de Habilitacao (CNH) brasileiras.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('9f0ad8aa-a3af-4187-b5c6-583089ab6331', 'certidao-casamento', 2, 'Analise esta Certidao de Casamento brasileira.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('a631d1ae-886e-4d71-bf19-097258fdd486', 'certidao-nascimento', 2, '## REGRAS CRITICAS - LEIA COM ATENCAO
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('2ab7ce2f-fdf4-450c-8299-da0d7002a21b', 'matricula-imovel', 2, '# PROMPT PARA ANALISE DE MATRICULA DE IMOVEL
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('a3c567d3-a011-42ab-97eb-5bee633a580a', 'itbi', 2, '## REGRAS OBRIGATORIAS
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('56e8a0cc-edb4-4fe5-99c6-0d3f5f3b235e', 'iptu', 2, 'Analise este documento de IPTU ou Certidao de Dados Cadastrais do Imovel.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('a546990e-7b2a-4420-9358-65bd68c02672', 'escritura', 2, 'Analise esta Escritura Publica (compra e venda, doacao, permuta, etc).
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('65a6a5ba-a20c-4934-960b-13a9d76532b6', 'compromisso-compra-venda', 2, '# PROMPT PARA EXTRACAO DE COMPROMISSO DE COMPRA E VENDA
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('bbad64b5-cc9d-490c-8de0-f8476c682061', 'contrato-social', 2, 'Analise este Contrato Social ou documento empresarial brasileiro.
INSERT INTO public.agentes_especialistas_prompts (id, agent_slug, versao, system_prompt, nome_exibicao, descricao, categoria, ativo, criado_por, created_at, updated_at) VALUES ('c9cc5f41-f6b6-4957-b508-08e7a39618f6', 'cndt', 2, '## REGRAS OBRIGATORIAS
